dataset_config:
  clvqa_comb:
    data_dir: /home/stan/.cache/torch/mmf/data/datasets
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    features:
      train:
      - gqa/defaults/features/gqa.lmdb
      - textvqa/defaults/features/open_images/detectron.lmdb,textvqa/ocr_en/features/ocr_en_frcn_features.lmdb
      val:
      - gqa/defaults/features/gqa.lmdb
      - textvqa/defaults/features/open_images/detectron.lmdb,textvqa/ocr_en/features/ocr_en_frcn_features.lmdb
      test:
      - gqa/defaults/features/gqa.lmdb
      - textvqa/defaults/features/open_images/detectron.lmdb,textvqa/ocr_en/features/ocr_en_frcn_features.lmdb
    annotations:
      train:
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_object_train_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_attribute_train_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_relation_train_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_logical_train_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_knowledge_train_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_scenetext_train_v0.1.npy
      val:
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_object_val_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_attribute_val_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_relation_val_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_logical_val_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_knowledge_val_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_scenetext_val_v0.1.npy
      test:
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_object_val_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_attribute_val_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_relation_val_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_logical_val_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_knowledge_val_v0.1.npy
      - /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/fcl_mmf_scenetext_val_v0.1.npy
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          max_length: 20
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/vocab/vocabulary_100k.txt
          preprocessor:
            type: simple_sentence
            params: {}
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          max_seq_length: 20
      answer_processor:
        type: m4c_answer
        params:
          vocab_file: /home/stan/ai_assistant/functional_continual_learning_dev/Gen_data/vocab/clvqa_answer_6k.txt
          preprocessor:
            type: simple_word
            params: {}
          num_answers: 10
          context_preprocessor:
            type: simple_word
            params: {}
          max_length: 50
          max_copy_steps: 12
      context_processor:
        type: fasttext
        params:
          max_length: 50
          model_file: wiki.en.bin
      ocr_token_processor:
        type: simple_word
        params: {}
      bbox_processor:
        type: bbox
        params:
          max_length: 50
      copy_processor:
        type: copy
        params:
          max_length: 100
      phoc_processor:
        type: phoc
        params:
          max_length: 50
    return_features_info: true
    use_ocr: true
    use_ocr_info: true
    use_order_vectors: true
    zoo_requirements:
    - textvqa.defaults
    - textvqa.ocr_en
    - gqa.defaults
    