model_config:
  unicl_debug:
    lr_scale_frcn: 0.1
    lr_scale_text_bert: 0.1
    lr_scale_mmt: 1.0
    text_bert_init_from_bert_base: true
    text_bert_resize_token_ocr: true
    use_cls: false
    text_bert:
      num_hidden_layers: 3
    obj:
      mmt_in_dim: 2048
      dropout_prob: 0.1
    ocr:
      mmt_in_dim: 3002
      dropout_prob: 0.1
    mmt:
      hidden_size: 768
      num_hidden_layers: 4
      max_position_embeddings: 800
    classifier:
      type: linear
      ocr_max_num: 50
      ocr_ptr_net:
        hidden_size: 768
        query_key_size: 768
      params: {}
    model_data_dir: /workspace/stan/.cache/torch/mmf/data
    losses:
    - type: m4c_decoding_bce_with_mask
    model: unicl_debug
